### ISSUE TITLE
Touch support is not working on RPI Display

### ISSUE THREAD

**Issue by sobrinho** [TinkerBoard/android-7.1.2_kernel#1]
Derived from https://github.com/TinkerBoard/debian_kernel/issues/24.

Android 6 is having trouble to detect that the screen has rotated and Android 7 is not working the touch screen at all.

**Comment by jamess-huang** [comment]
Hi, sobrinho
    https://drive.google.com/open?id=1qO7V9p2HAbarlkvKzjnoF4N6IiBzVJq6
    We can not duplicate the issue on Android N, above is the video, can you help to confirm ?
    By the way, the reason that the Android N has no this issue is because we do not rotate the screen when launch the app.

**Comment by sobrinho** [comment]
Is this the Raspberry Display 7"?

Can you confirm me which version exactly are you running?

**Comment by sobrinho** [comment]
Okay, just figured out that it won't work on first boot but after restarting two times it just started working for whatever reason 😱
