### ISSUE TITLE
No SIM Card

### ISSUE THREAD

**Issue by sobrinho** [TinkerBoard/android-7.1.2_kernel#11]
Hi there,

Compiling from the source I see a warning of no SIM card while the released image on the Asus site doesn't have it.

Probably something is missing from the repo?

![img_4717](https://user-images.githubusercontent.com/26460/49187585-1aa83f80-f34f-11e8-84e3-367ea4f0622c.jpg)
![img_4718](https://user-images.githubusercontent.com/26460/49187587-1aa83f80-f34f-11e8-99c0-a8c58f385990.jpg)

**Comment by jamess-huang** [comment]
Dear, sobrinho
That's the function we test on develop branch. We are not sure if it works or not and we will disable this function in the future release. You can ignore this or If you want to download the code base which is mapping to the current release, you can run the below command.

$ repo init -u https://git@bitbucket.org/TinkerBoard_Android/manifest.git -b sbc/tinkerboard/asus/Android-7.1.2
$ repo sync -d
#switch to the released code base
$ repo init -m android_20180817_v14.1.2.50.xml
#repo sync the code base again
$ repo sync -d --no-tags

**Comment by sobrinho** [comment]
Thanks!
