### ISSUE TITLE
RPi Display resolution

### ISSUE THREAD

**Issue by sobrinho** [TinkerBoard/android-7.1.2_kernel#12]
Hi there!

RPi Display claims to be 800x480 240dpi but looking into wm size, I'm seeing 1280x720.

```
rk3288:/mnt/sdcard/Download # wm size
Physical size: 1280x720
rk3288:/mnt/sdcard/Download # wm density
Physical density: 240
```

Changing to 800x480 improves the quality of the graphics but bugs the 1) android boot image 2) the soft keys (volume controls disappear, probably because they don't fit).

1280x720
![img_4761](https://user-images.githubusercontent.com/26460/49748772-cb86d680-fc8d-11e8-8197-ab60fb88cca9.JPG)
![img_4762](https://user-images.githubusercontent.com/26460/49748774-cc1f6d00-fc8d-11e8-855a-5d67c58017b2.JPG)

800x480
![img_4763](https://user-images.githubusercontent.com/26460/49748775-cc1f6d00-fc8d-11e8-80b1-08bc0561a326.JPG)
![img_4764](https://user-images.githubusercontent.com/26460/49748776-ccb80380-fc8d-11e8-8e03-838cbb845aa2.JPG)

**Comment by fogoat** [comment]
I remember with ODroid, there were some chipset limitations on display resolutions supported. I wonder if this is the same situation for TinkerBoard. I was able to display on a 1680x1050, but the bottom was chopped off for me. Maybe closest resolution supported is not something desktop monitors support. I'm surprised a tablet sized resolution isn't perfect. We got so many display resolutions compared to Apple hardware, it is a difficult beast to deal with.

**Comment by jamess-huang** [comment]
Dear, sobrinho
    We set this value in the framework, you can modify the framework to have a try.
    Please reference the below link
    https://bitbucket.org/TinkerBoard_Android/frameworks-native/commits/eda525e24e34def17ed722d3d21bf12100eac980?at=sbc/tinkerboard/asus/Android-7.1.2
    If you want to change the frame buffer size, you can modify the property value to 800x480 at
    line 193 in frameworks/native/services/surfaceflinger/SurfaceFlinger.cpp
    and also
    line 241 in frameworks/native/services/surfaceflinger/SurfaceFlinger_hwc1.cpp

**Comment by sobrinho** [comment]
I'm able to set the desired resolution but then the Android is a bit odd, probably because it is too small.

I was just wondering if this was intentional or what.

**Comment by sobrinho** [comment]
@jamess-huang gotcha! Saw your comment after published mine.

Since RPi display is 800x480, does it make sense to be that resolution by default?

**Comment by jamess-huang** [comment]
Did it work to change the frame buffer size to 800x480 on your side ?
To change the frame buffer size to 720p is in order to have a more beautiful display content. But if there will be any side effect, we can change it back.

**Comment by sobrinho** [comment]
It worked, although the resolution is a bit weird, using 800x480 it displays perfectly on the display but seems like everything is too big for the screen.

Although, since I can change on my side, that's fine.

Closing, thanks again!

**Comment by jamess-huang** [comment]
Maybe you can adjust the option which located at "settings --> Developer options --> Smallest width"
