### ISSUE TITLE
system crash randomly and board loses power

### ISSUE THREAD

**Issue by umeshjaiswal20** [TinkerBoard/android-7.1.2_kernel#15]
I have a HDMI touch display connected to tinker board. The issue with this image is that it randomly crashes and the board does not even reboot after that. The power LED's on the board are also off and needs power cable unplug-plug to start again. Unable to debug error.

**Comment by jamess-huang** [comment]
Dear, umeshjaiswal
    What is the power source of the HDMI touch display ? Does it have an external power supply or it is powered by Tinker's USB port ? If powered by Tinker's USB port, may I know your AC adaptor SPEC ? We suggest 5V/3A will be better and 5V/2.5A at least.

**Comment by umeshjaiswal20** [comment]
Dear Jamess,
    Thank you for your prompt reply. As for your query I am using a Ac
adapter with output of 5.2V 1.8A. for tinker and the display is on another
adapter with 12V 1A output. So, as you suggested I will try a new power
source for tinker with given specs and see if issue exists.
    Also I have a query regarding video playback from local storage. I
tried to play a downloaded file inside webview but it gives error on logcat
'file not found'. And yes I have given the correct path. If any suggestions
please reply.

**Comment by jamess-huang** [comment]
May I know what is your step of playing the video

**Comment by umeshjaiswal20** [comment]
> May I know what is your step of playing the video

Well I am using Ionic to develop an app. So what i need is to play the video in html5 <video> tag which is under the webview of the app. But the problem is whenever I give the path of the file i.e. 'file:///storage/...'  it does not playback. Also I tried the app on android phone with video in apps local storage which plays fine but on tinker board it does not play.

**Comment by alex3788** [comment]
Hi,
I tried the URI "file:///sdcard/Movies/1.mp4" it is work for me.
Please check the attached pic.

![screenshot_20190225-072438](https://user-images.githubusercontent.com/30650711/53320799-bbd47100-3911-11e9-9385-3b5996ce760e.png)

**Comment by umeshjaiswal20** [comment]
> Hi,
> I tried the URI "file:///sdcard/Movies/1.mp4" it is work for me.
> Please check the attached pic.
> 
> ![screenshot_20190225-072438](https://user-images.githubusercontent.com/30650711/53320799-bbd47100-3911-11e9-9385-3b5996ce760e.png)

I am using ionic to build my app.How did you build it? Can you show me some code snippets that may be helpful.

**Comment by alex3788** [comment]
Hi umeshjaiswal20,

I didn't use ionic to build app. I just open browser and type "file:///sdcard/Movies/1.mp4" in address bar and test it is work.

**Comment by umeshjaiswal20** [comment]
Thank you! Jamess and alex3788 for your help. I have resolved the system crash issue using a better power source as suggested and it worked. The video playback issue was from ionic build. Since alex pointed out that videos play in browser it was easier to debug error.The error was I was requesting for file even before loading of app. Kudos! closing issue.
