### ISSUE TITLE
Waze is not compatible

### ISSUE THREAD

**Issue by sobrinho** [TinkerBoard/android-7.1.2_kernel#3]
Hi there!

For some reason, the Waze is the only application so far that I'm seeing that is not compatible with this Android version.

Maybe it is related to the Waze development itself but on Android 6 at the same board it is working as expected and I'm not aware of anybody complaining that Waze isn't compatible with Android 7.

Maybe something related to the version of Android at the image? I don't know.

![img_4578](https://user-images.githubusercontent.com/26460/46217587-c534bf80-c318-11e8-9a20-a02f45eac1db.jpg)

**Comment by sobrinho** [comment]
Installing by the APK (from apkmirror) it works but still shows that message.

**Comment by jamess-huang** [comment]
Dear, Sobrinho
    When user uploads the apk to the Google play, user can set some criteria to check if the device can support this app or not. For example, the app may need the device to support GPS, Gsensor, FHD resolution and so on. The error message you see is because there are some criteria that the app needs but TinkerBoard cannot meet. (I guess). So does it work well if you install the apk from apkmirror ?

**Comment by sobrinho** [comment]
Yep, it is working perfectly so far 🤔 

There is any way to check which requirement is missing for it?

**Comment by jamess-huang** [comment]
Sorry, I am not familiar with app development. But I think it should have some tool to check this.
