### ISSUE TITLE
Display brightness is not working on RPI Display

### ISSUE THREAD

**Issue by sobrinho** [TinkerBoard/android-7.1.2_kernel#4]
Hi there!

Changing display brightness is not working on Android 7 but it works on Android 6.

**Comment by jamess-huang** [comment]
We will check and feedback to you.

**Comment by sobrinho** [comment]
More information, when I try to change the backlight on UI, I got this on dmesg:

```
[25262.057062] type=1400 audit(1538419170.522:51): avc: denied { read } for pid=784 comm="ndroid.systemui" name="usb" dev="tmpfs" ino=8589 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:usb_device:s0 tclass=dir permissive=1
[25262.057202] type=1400 audit(1538419170.522:52): avc: denied { open } for pid=784 comm="ndroid.systemui" path="/dev/bus/usb" dev="tmpfs" ino=8589 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:usb_device:s0 tclass=dir permissive=1
[25262.058490] type=1400 audit(1538419170.522:53): avc: denied { create } for pid=784 comm="ndroid.systemui" scontext=u:r:platform_app:s0:c512,c768 tcontext=u:r:platform_app:s0:c512,c768 tclass=netlink_kobject_uevent_socket permissive=1
[25262.058587] type=1400 audit(1538419170.522:54): avc: denied { bind } for pid=784 comm="ndroid.systemui" scontext=u:r:platform_app:s0:c512,c768 tcontext=u:r:platform_app:s0:c512,c768 tclass=netlink_kobject_uevent_socket permissive=1
[25262.058671] type=1400 audit(1538419170.522:55): avc: denied { setopt } for pid=784 comm="ndroid.systemui" scontext=u:r:platform_app:s0:c512,c768 tcontext=u:r:platform_app:s0:c512,c768 tclass=netlink_kobject_uevent_socket permissive=1
[25262.059192] type=1400 audit(1538419170.522:56): avc: denied { read } for pid=784 comm="ndroid.systemui" scontext=u:r:platform_app:s0:c512,c768 tcontext=u:r:platform_app:s0:c512,c768 tclass=netlink_kobject_uevent_socket permissive=1
```

**Comment by sobrinho** [comment]
Also, looking around in dmesg:

```
rk3288:/ # dmesg | grep backlight
[    0.563481] pwm-backlight backlight: GPIO lookup for consumer enable
[    0.563496] pwm-backlight backlight: using device tree for GPIO lookup
[    0.563528] of_get_named_gpiod_flags: parsed 'enable-gpios' property of node '/backlight[0]' - status (0)
[    0.563574] backlight supply power not found, using dummy regulator
```

**Comment by sobrinho** [comment]
I'm almost a noob on compiling Android, drivers and such but I can tell there was a commit adding support for Debian here: https://github.com/TinkerBoard/debian_kernel/commit/d1a84d6d1a76246ce37dfe92160d31ed45bdcb6c

Looking at the driver for 6.0.1 [here](https://github.com/TinkerBoard/android-6.0.1_kernel/blob/develop/drivers/misc/tinker_mcu.c) and for 7.1.2 [here](https://github.com/TinkerBoard/android-7.1.2_kernel/blob/develop/drivers/misc/tinker_mcu.c) they have a lot of differences (not sure if a patch is missing or due to Android version itself).

**Comment by jamess-huang** [comment]
Thanks for your information. We have solved this problem. But it needs to rebuild the android system image. Below are the fix commits. 
https://bitbucket.org/TinkerBoard_Android/rk-device-rockchip-rk3288/commits/e57382fe021e651a01d3b3f6b3df21a6f5ed19d1?at=sbc/tinkerboard/asus/Android-7.1.2
https://bitbucket.org/TinkerBoard_Android/rk-hardware-rk29-liblights/commits/328c79ed5b3fd8eebe509b97045a4ad6603f934b?at=sbc/tinkerboard/asus/Android-7.1.2

We need some time to do the formal release process, You can rebulid the android image by yourself. Please check out the below link.
https://tinkerboarding.co.uk/wiki/index.php/Software#How_to_build_Android.28AOSP.29_source_code

**Comment by sobrinho** [comment]
Thanks!

I will try to compile to see if the problem is fixed!

**Comment by sobrinho** [comment]
Is it possible to compile that on macOS?

The first step already failed:

```
pwd:u-boot   ref:(8ebb45f6c4...)   ruby:2.4.2   node:v9.10.1   status:0
λ make -j4
/Users/sobrinho/Developer/tinkerboard/u-boot/../prebuilts/gcc/linux-x86/arm/arm-eabi-4.8/bin/arm-eabi-gcc: /Users/sobrinho/Developer/tinkerboard/u-boot/../prebuilts/gcc/linux-x86/arm/arm-eabi-4.8/bin/arm-eabi-gcc: cannot execute binary file
/bin/sh: /Users/sobrinho/Developer/tinkerboard/u-boot/../prebuilts/gcc/linux-x86/arm/arm-eabi-4.8/bin/arm-eabi-gcc: cannot execute binary file
usage: dirname path
scripts/kconfig/conf --silentoldconfig Kconfig
  CHK     include/config.h
  UPD     include/config.h
  GEN     include/autoconf.mk
  GEN     include/autoconf.mk.dep
/bin/sh: /Users/sobrinho/Developer/tinkerboard/u-boot/../prebuilts/gcc/linux-x86/arm/arm-eabi-4.8/bin/arm-eabi-gcc: cannot execute binary file
/bin/sh: /Users/sobrinho/Developer/tinkerboard/u-boot/../prebuilts/gcc/linux-x86/arm/arm-eabi-4.8/bin/arm-eabi-gcc: cannot execute binary file
make[2]: *** [include/autoconf.mk] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [include/autoconf.mk.dep] Error 1
make[1]: *** [silentoldconfig] Error 1
make: *** No rule to make target `include/config/auto.conf', needed by `include/config/uboot.release'.  Stop.
```

**Comment by sobrinho** [comment]
Compiling is not working on Ubuntu 18.04:

```
sobrinho@ubuntu:/mnt/hgfs/tinkerboard/u-boot$ make rk3288_secure_defconfig
#
# configuration written to .config
#
sobrinho@ubuntu:/mnt/hgfs/tinkerboard/u-boot$ make -j4
make: *** No rule to make target '/Users/sobrinho/Developer/tinkerboard/u-boot/include/common.h', needed by 'include/config/auto.conf'.  Stop.
```

**Comment by sobrinho** [comment]
Error compiling the kernel on Ubuntu 18.04:

```
  CC      net/netfilter/xt_CONNSECMARK.o
  CC      net/netfilter/xt_LOG.o
  CC      net/netfilter/xt_NETMAP.o
  CC      net/netfilter/xt_NFLOG.o
  CC      net/netfilter/xt_NFQUEUE.o
  CC      net/netfilter/xt_REDIRECT.o
  CC      net/netfilter/xt_SECMARK.o
  CC      net/netfilter/xt_TPROXY.o
make[2]: *** No rule to make target 'net/netfilter/xt_TCPMSS.o', needed by 'net/netfilter/built-in.o'.  Stop.
scripts/Makefile.build:411: recipe for target 'net/netfilter' failed
make[1]: *** [net/netfilter] Error 2
Makefile:1011: recipe for target 'net' failed
make: *** [net] Error 2
```

**Comment by sobrinho** [comment]
Just to confirm, it fixed after compiling :shipit:

**Comment by sobrinho** [comment]
Seems like the Android now "supports" SIM cards, which I don't remember to see anything about using the released version in TinkerBoard site (maybe some config that is not published that is needed?).

Also, not sure if it is related, but I'm seeing a warning when the device boots.

![img_4601](https://user-images.githubusercontent.com/26460/46623587-70f1c280-cb04-11e8-9007-4537b3543d6f.jpg)

**Comment by sobrinho** [comment]
This message got fixed by that command on adb shell:

```bash
busybox egrep "^ro\.build\.(date(\.utc)?|fingerprint)=" /system/build.prop | busybox sed -e"s/^ro\./ro.vendor./" > /vendor/build.prop
```

Kudos to https://forum.xda-developers.com/nexus-9/development/fix-build-prop-variety-fix-aka-contact-t3133347

**Comment by sobrinho** [comment]
One more information, when the display sleeps but we have the "Stay awake" enabled, wherever you touch on the screen will wake up the screen but also touch at this position.

This may be a bit annoying because you may touch somewhere you don't want like enabling/disabling a toggle if the display slept in a settings screen, or even open an app if it slept on launcher page.

The trick right now is to perform a slide from top to bottom, to open the status bar because that doesn't trigger any action.

**Comment by jamess-huang** [comment]
This problem is caused by the mismatch between these 2 properties ro.build.fingerprint and  ro.vendor.build.fingerprint.

You can also add below patch to fix this issue.

diff --git a/core/Makefile b/core/Makefile
index 1b024b404..68ceecdd5 100644
--- a/core/Makefile
+++ b/core/Makefile
@@ -81,6 +81,9 @@ ADDITIONAL_DEFAULT_PROPERTIES += \
 ADDITIONAL_DEFAULT_PROPERTIES := $(call uniq-pairs-by-first-component, \
     $(ADDITIONAL_DEFAULT_PROPERTIES),=)
 
+$(shell rm -f $(PRODUCT_OUT)/system/build.prop)
+$(shell rm -f $(call intermediates-dir-for,ETC,system_build_prop)/build.prop)
+
 intermediate_system_build_prop := $(call intermediates-dir-for,ETC,system_build_prop)/build.prop
 
 $(INSTALLED_DEFAULT_PROP_TARGET): $(intermediate_system_build_prop)
