### ISSUE TITLE
Volume level is too low on P2 output

### ISSUE THREAD

**Issue by sobrinho** [TinkerBoard/android-7.1.2_kernel#7]
Hi there again,

I'm not sure if this is a hardware or software problem but the output is kind of low at the P2 output.

Using a Sennheiser Momentum in an iPhone 5s I have almost the same "volume" level of TB, comparing both at 100% of volume (the iPhone still wins but just for a bit [volume, not the quality itself]) (both running the same song on Spotify at high-quality).

That's completely fine for the headphone but the major difference is when the TB is plugged at my car in the auxiliary input.

Using the same iPhone at the car the volume level is good enough around 10-12 of volume in my car (iPhone on 100% of volume) (less than 45% of car's total volume) without any kind of noise but when I'm using the TB the sound is at the same level only around 20-22 in my car (TB on 100% of volume) (around 88% of car's total volume).

The sound system goes until 25 but if I do that using the iPhone the speakers almost blow.

The problem is that when the sound system is at this level, the TB is sending a lot of noise (really a lot) and if I keep at that volume and accidentally change the source to be Radio or another device, the speakers almost kill me by a heart attack.

Note that the problem is not the sound of the car (since it works with other devices perfectly fine and I'm using the same P2/P2 cable) but the TB for whatever reason (and do not seem to be a power issue since the device is not warning me about low voltage or anything like that).

_Probably this is not the right place to report but I'm assuming that it may be a software problem of some kind, I have no idea. Maybe I can try another OS to confirm that?_

**Comment by jamess-huang** [comment]
I am not sure how you connect the car and the TB. Could me give me an illustration diagram ?

**Comment by sobrinho** [comment]
I'm using a P2/P2 cable between the Tinker Board and the car AUX INPUT (the 3.5mm jack).

![13099805_1sz](https://user-images.githubusercontent.com/26460/47450627-1b701380-d79c-11e8-806c-b5c44b63e69d.jpg)

**Comment by jamess-huang** [comment]
Dear, sobrinho
    Can you try to play the music file by the below command and help to feedback the result to us. Thanks.
    $ tinyplay MusicFile.wav  -D 3 -d 2

**Comment by sobrinho** [comment]
@jamess-huang this would work using Android? Any song?

I'm using Spotify right now but I can find some music to test that.

**Comment by jamess-huang** [comment]
Yes, Any song and it will work on android.
This is just for test.

**Comment by sobrinho** [comment]
How nice, my TB doesn't want to turn on anymore.

No power in any GPIO pin, the power source is fine.

😭

**Comment by sobrinho** [comment]
Apparently, there is no way to buy a new one in Brazil, no sellers in our eBay like e-commerce.

I bought mine while I was on the USA a few months ago.

Recommendations?

Asus is widely available here but I'm not seeing any Tinker Board seller around here.

**Comment by sobrinho** [comment]
Importing through Amazon is ridiculously pricey, shipping and import fees are greater than the product price itself.

$69.99 + $77.95 Shipping & Import Fees Deposit to Brazil

**Comment by sobrinho** [comment]
Ouch, powering through GPIO is working, probably the MicroUSB port died then.

**Comment by sobrinho** [comment]
Used an online converter from youtube to mp3 and another one from mp3 to wav, both are playing fine in the computer.

TB is not playing:

```
rk3288:/mnt/sdcard/Download # tinyplay iron.wav -D 3 -d2
Sample rate is 44100Hz, device only supports <= 8000Hz
```

**Comment by jamess-huang** [comment]
Please use this file to test
https://drive.google.com/open?id=1nhYv4gppcYtY-LRkFfFZHbsDZ3vUfF23

**Comment by sobrinho** [comment]
Same issue:

```
rk3288:/mnt/sdcard/Download # tinyplay Testfile.wav -D 3 -d2
Sample rate is 44100Hz, device only supports <= 8000Hz
```

**Comment by jamess-huang** [comment]
Dear, sobrinho
    Please notice that there is a space between "-d" and "2"
    rk3288:/mnt/sdcard/Download # tinyplay Testfile.wav -D 3 -d 2

**Comment by sobrinho** [comment]
For whatever reason, it is working as expected now.

Not too loud as my iPhone 5S but at least the same volume as the FM, I don't need more than that.

Closing, thanks again!
